### ISSUE TITLE
APi should reject Products which are created as a duplicate

### ISSUE THREAD

**Issue by zergar** [freitagsrunde/k4ever-backend#18]
Duplicate check should be based on name, Price and Deposit

**Comment by phiphi282** [comment]
While im with you, that we should have some sort of duplicate check for products, I'm not so sure if the check should be based on the name, price and deposit.

If we want to have the possibility to have multiple products with the same name I would suggest to make the check based on the barcode for example.
Otherwise I would probably use just the product name instead to avoid confusion with multiple products having the same name.

**Comment by zergar** [comment]
It might be possible to do a frontend-check on entering new items which would suggest similar items to prevent double entries. Though I#m not sure whether the barcode should be the only deciding aspect when checking for duplicates since any user might not see the relevence of the barcode for this purpose. I'd suggest to at least include the name of the product since any duplicate names are confusing for the end user.
